### PR TITLE
JENKINS-55805: handle long lines more flexible

### PR DESCRIPTION
**Pull request by rbri**
make the line handling more flexible to be able to process really long lines

### CODE REVIEW

**Comment by uhafner** [comment]
I wonder if it is really required to break the API and change so many files. Wouldn't it be much simpler to let the `isLineInteresting` method to simply return `false` on lines of length > 4000?

**Comment by rbri** [comment]
Of course this is not required but the idea was to implement it in a way to handle similar situations for all the parsers. From my point of view simply ignoring too long lines is not so good.

**Comment by rbri** [comment]
BTW. Does any other module use this?

**Comment by uhafner** [comment]
Simplified your solution: https://github.com/jenkinsci/analysis-model/commit/920f25e82b3486ed9ec9979a29a472303fa1f07c.

**Comment by uhafner** [comment]
Otherwise we are risking that custom parser plugins will break.

**Pull request closed without merging**
