### PR TITLE
Sarif report: allow file paths in file URI scheme

### PR DESCRIPTION
**Pull request by theKBro**
see https://issues.jenkins.io/browse/JENKINS-73933

file paths in file uri scheme are converter to normal paths

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by theKBro** [comment]
If an exception occurs it falls back to the old value

**Comment by theKBro** [comment]
I added test data to the testcase to clarify this -> its getting translated

**Comment by theKBro** [comment]
current solution seems to work under windows only...
any proposal how to improve the code?

**Review by uhafner — APPROVED** [review]
Thanks for starting this PR! I directly committed some changes, since I didn't find a solution without coding it directly...

**Pull request merged**
