### PR TITLE
Add support for parsing cargo check JSON output

### PR DESCRIPTION
**Pull request by garyttierney**
Adds a parser that can read compiler messages emitted by rustc and clippy in
the format used by cargo's `--message-format json` option.

This allows producing analysis reports for Rust projects using either the standard `cargo check` functionality, or the clippy tool.

Also, I think I need to add the parser definition to the Jenkins `warnings-ng-plugin` too. Should I send a PR for that now or wait until this new parser is available in the latest snapshot of analysis-model?

### CODE REVIEW

**Comment by uhafner** [comment]
Can you please also add a line to the ChangeLog?

**Comment by garyttierney** [comment]
Thanks for the review! I'll action these changes a bit later today.

**Comment by uhafner** [comment]
Thanks! I'll ping you if the release (or snapshot) is published so we can use it in warnings-ng.

**Comment by uhafner** [comment]
If you want to change something or add icon, help, etc, please file a PR to warning-ng:

https://github.com/jenkinsci/warnings-ng-plugin/commit/fcf33e4cd1757da9be4707712762488ddc5050b1

**Pull request merged**
