### PR TITLE
[EmbeddedEnginee] Support native .log file format

### PR DESCRIPTION
**Pull request by evahabeeballah**
There are enhancements done by the Embedded Engineer tool that produced a new format of the .log file being parsed. And also new type of Warning/Error was introduced. So The parser was edited accordingly. 

Relevant pull-request : https://github.com/jenkinsci/analysis-model/pull/879
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by uhafner** [comment]
> There are enhancements done by the Embedded Engineer tool that produced a new format of the .log file being parsed. 

Typically, parsers in my library are expected to be backward compatible. I.e., read the old and new format. How are you planning to achieve that? Otherwise you will break the builds for other consumers that use the old version.

**Comment by fubian** [comment]
> > There are enhancements done by the Embedded Engineer tool that produced a new format of the .log file being parsed.
> 
> Typically, parsers in my library are expected to be backward compatible. I.e., read the old and new format. How are you planning to achieve that? Otherwise you will break the builds for other consumers that use the old version.

The "new" log format is the native log of the tool. Before we were not aware of that log and we used the standard output of the tool redirected to a file as log file. This was more a work-around and the format now is the proper way.

**Comment by evahabeeballah** [comment]
> This PR requires an update of the warnings plugin test case as well (when released).

Yes, I will also update the log file used in the warnings plugin

**Comment by evahabeeballah** [comment]
Hi @uhafner, Is there something to be done from my side for this pull request? 
Thanks :)

**Review by uhafner — APPROVED** [review]

**Pull request merged**
