### PR TITLE
Ignore timestamper-plugin 1.9 prefixes when parsing Clang log messages.

### PR DESCRIPTION
**Pull request by smokris**
See https://issues.jenkins-ci.org/browse/JENKINS-56484

### CODE REVIEW

**Comment by smokris** [comment]
Hmm, https://ci.jenkins.io/blue/rest/organizations/jenkins/pipelines/Plugins/pipelines/analysis-model/branches/PR-128/runs/1/nodes/13/log/?start=0 says "BUILD SUCCESS" yet GitHub's indicator says "This commit cannot be built"…

**Comment by uhafner** [comment]
That's why I build with travis, too :)

**Comment by uhafner** [comment]
I also linked JENKINS-56484 with JENKINS-48344. 

Your fix works well for Clang, but all other parsers will still have the same problem.

**Comment by smokris** [comment]
Ah, I see.  Per your comments on JENKINS-56484, it sounds like you have a more general plan, so I'll close this.

**Comment by uhafner** [comment]
Puh, you are quite fast. I thought we could discuss this here :-) Maybe it makes sense to publish your solution until a general fix is available...

**Comment by uhafner** [comment]
I just wondered if the format you are excluding is working for all variants of timestamps of the timestamper plugin...

**Comment by smokris** [comment]
> I just wondered if the format you are excluding is working for all variants of timestamps of the timestamper plugin...

Good point; after looking at this some more, I'm doubtful that my solution would work (the new test passes, but I think the test datum may be wrong).

timestamper-plugin appears to always [use a format similar to ISO_OFFSET_DATE_TIME when it modifies log files](https://github.com/jenkinsci/timestamper-plugin/blob/master/src/main/java/hudson/plugins/timestamper/pipeline/GlobalDecorator.java#L52), and then it [reformats the timestamps for display](https://github.com/jenkinsci/timestamper-plugin/blob/master/src/main/java/hudson/plugins/timestamper/action/TimestampsActionOutput.java#L170).

It provides a UI that lets you choose the display format:
Screenshot of the timestamper-plugin configuration form

But I'm not sure offhand whether `ClangParser` sees the on-disk timestamp format or the reformatted timestamp.

**Comment by uhafner** [comment]
I see. I'll run a build and see what is written to disk. If the user can enter anything as template then it will be impossible to write a filter...

**Comment by uhafner** [comment]
Ok, if I look into the file on disk the format is completely different:

```
[2019-03-22T19:48:57.065Z] Started by user [8mha:////4J+qCmYER23H1hNCmYVB1Cr9b8PsmRj81Kat24WLCk7AAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
[2019-03-22T19:48:57.094Z] Checking out git https://github.com/jenkinsci/analysis-model.git into /var/jenkins_home/workspace/pipeline-analysis-model@script to read Jenkinsfile.analysis
[2019-03-22T19:48:57.139Z] No credentials specified
[2019-03-22T19:48:57.143Z]  > git rev-parse --is-inside-work-tree # timeout=10
[2019-03-22T19:48:57.304Z] Fetching changes from the remote Git repository
[2019-03-22T19:48:57.305Z]  > git config remote.origin.url https://github.com/jenkinsci/analysis-model.git # timeout=10
[2019-03-22T19:48:57.462Z] Fetching upstream changes from https://github.com/jenkinsci/analysis-model.git
[2019-03-22T19:48:57.462Z]  > git --version # timeout=10
[2019-03-22T19:48:57.607Z]  > git fetch --tags --force --progress https://github.com/jenkinsci/analysis-model.git +refs/heads/*:refs/remotes/origin/*
[2019-03-22T19:48:59.211Z]  > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
[2019-03-22T19:48:59.348Z]  > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
[2019-03-22T19:48:59.464Z] Checking out Revision 4d307630badf2f9efcfea6d31fb5ac2655153cc2 (refs/remotes/origin/master)
[2019-03-22T19:48:59.468Z]  > git config core.sparsecheckout # timeout=10
[2019-03-22T19:48:59.584Z]  > git checkout -f 4d307630badf2f9efcfea6d31fb5ac2655153cc2
[2019-03-22T19:49:00.841Z] Commit message: "Fixed some warnings."
```
I can toggle in the UI different visualizations so this seems to be fixed on disk and changes only in the UI, that is good.

**Comment by uhafner** [comment]
Conversely, your approach will not work on a real console log. Did you test the changed module file in Jenkins?

**Comment by uhafner** [comment]
I think we need to clean all lines with a regex that matches e.g. `[2019-03-22T19:49:00.841Z]`, that shouldn't be hard. Do you want to give it a try? Otherwise I would hand over that issue to one of my Students in my testing course...

**Comment by smokris** [comment]
> Did you test the changed module file in Jenkins?

No, I had only tested `analysis-model` in isolation (`mvn test`).  (Sorry, I should have fully tested before submitting this PR.)

> I think we need to clean all lines with a regex that matches e.g. [2019-03-22T19:49:00.841Z]

That works (I tested it in a full Jenkins dev environment, using the Pipeline at the top of https://issues.jenkins-ci.org/browse/JENKINS-56484).

I submitted https://github.com/jenkinsci/analysis-model/pull/130 (GitHub won't let me reopen this PR since I deleted my fork).

(I don't yet know enough about the structure of this group of plugins to develop a more general fix that would apply to all parsers.  On https://issues.jenkins-ci.org/browse/JENKINS-56484 you mentioned `ConsoleNotesFilter` — I imagine I could follow that pattern, but I haven't found a class by that name.)

**Pull request closed without merging**
