### PR TITLE
Added SonarQube parsers

### PR DESCRIPTION
**Pull request by CarlesCapdevila**
Added two parsers for SonarQube as in the [Warnings ](https://github.com/jenkinsci/warnings-plugin/pull/143)plugin:
- SonarQube Issues -> Used to parse issues retrieved from the SonarQube api (api/issues/search)
- SonarQube Diff -> Used to parse new issues retrieved from a SonarQube differential analysis

Some things that didn't go as expected and which made that the tests had to be changed:
- Line numbers below 0 (-1 in my case) are clipped to 0.
- Expected 32 issues and got 31; think that's because there was one which was nearly identical to other one and got filtered out of the report. Is that the case?

Thanks for your attention :)

### CODE REVIEW

**Comment by CarlesCapdevila** [comment]
Didn't had time to check out how to put the default pattern and icon, could you maybe please take care of that? :'D

Maybe put [these ](https://github.com/SonarSource/sonar-scanner-jenkins/tree/master/src/main/webapp/images) icons from the SQ scanner plugin?
and this default pattern: "**/target/sonar/sonar-report.json"?

**Comment by uhafner** [comment]
Thanks, I will add the pattern and icons...

**Comment by uhafner** [comment]
To answer your questions:
1) a line number must be a positive number, a zero indicates an issue for the whole file (i.e. a line number is not available or makes no sense). What is semantics of negative numbers in Sonar?
2) The reason that one issue is marked as duplicate is because all properties are the same. Seems that some issues do not have a line number attribute, so 2 issues are marked as equal (which are actually not). 

Shouldn't the block
```
			"textRange": {
				"startLine": 162,
				"endLine": 162,
				"startOffset": 0,
				"endOffset": 109
			},
```
be considered as well? (At least in cases where lineNumber is not given...

**Comment by CarlesCapdevila** [comment]
Very kind of you to check that and answer, thanks!
1.- It seems that it was me who arbitrarily put the -1 as default number, to make clear that there was no number.
2.- Yes, the "textRange" block should also be considered (only for SonarQubeIssuesParser). I didn't do it because AFAIK there's no "endLine" for the old warnings plugin and I didn't know if a change in behaviour from the warnings plugin would be bad. 

If there's no need for the parsers to have the same behaviour in the two plugins, this can be implemented in this one by adding [SonarQubeParser](https://github.com/SoftwareBuildService/analysis-model/blob/1ec6e8ee9a2e381eb3b0ebc6e5988a9c2e58f385/src/main/java/edu/hm/hafner/analysis/parser/SonarQubeParser.java).parseEnd() (like "[parseStart](https://github.com/SoftwareBuildService/analysis-model/blob/1ec6e8ee9a2e381eb3b0ebc6e5988a9c2e58f385/src/main/java/edu/hm/hafner/analysis/parser/SonarQubeParser.java#L166)()"), and then overriding parseStart() and parseEnd() on [SonarQubeDiffParser](https://github.com/SoftwareBuildService/analysis-model/blob/1ec6e8ee9a2e381eb3b0ebc6e5988a9c2e58f385/src/main/java/edu/hm/hafner/analysis/parser/SonarQubeDiffParser.java) and [SonarQubeIssuesParser](https://github.com/SoftwareBuildService/analysis-model/blob/1ec6e8ee9a2e381eb3b0ebc6e5988a9c2e58f385/src/main/java/edu/hm/hafner/analysis/parser/SonarQubeIssuesParser.java). This way we'd be solving both issues.

- SonarQubeIssuesParser should use the "[textRange.startLine](https://github.com/SoftwareBuildService/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/sonarqube-api-multimodule.json#L38)" and "[textRange.endLine](https://github.com/SoftwareBuildService/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/sonarqube-api-multimodule.json#L39)"; if there's not textRange block use "[line](https://github.com/SoftwareBuildService/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/sonarqube-api-multimodule.json#L2774)"; else 0.

- SonarQubeDiffParser should just use the "[startLine](https://github.com/SoftwareBuildService/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/sonarqube-differential-multimodule.json#L7)" and "[endLine](https://github.com/SoftwareBuildService/analysis-model/blob/master/src/test/resources/edu/hm/hafner/analysis/parser/sonarqube-differential-multimodule.json#L9)".

I understand that this is not really your task, so please let me know if you need my support :)

**Comment by uhafner** [comment]
I added the parser partially in the warnings plug-in now, see https://github.com/jenkinsci/warnings-plugin/commit/d5fa7872e78314bd858d07318538be8fc5ab26e4.

One thing that is not clear to me yet: how does a user decide which parser should be used?  (Diff or Issues). Or should both parsers run on the same file and automatically only one of them reports issues? Or does a user really need to select one of the parsers?

**Comment by uhafner** [comment]
I also merged you changes, otherwise I can't reference them in the other plug-in. 

The change you made for the *old* warnings plugin is kind of obsolete, the new 3.0 branch will hopefully released in august. So it makes sense to use all of the properties of the new API. So if you find some more time a subsequent PR would be nice ;-)

**Comment by CarlesCapdevila** [comment]
Cool, thank you! :)
Should be SonarQube instead of [SonarCube ](https://github.com/jenkinsci/warnings-plugin/commit/d5fa7872e78314bd858d07318538be8fc5ab26e4#diff-185698f1ff1a2cd59cf28ea19c11a0a8R20)though :'D if this is not relevant ignore it.

To answer your question: 
- Diff: This is used for SonarQube reports generated through a [preview ](https://blog.sonarsource.com/analysis-vs-preview-vs-incremental-preview-in-sonarqube)analysis. It only parses the newly introduced issues.
- Issues: This is used for reports obtained through the SonarQube api ("/api/issues/search" at the time of writing)

In our use case we use each parser depending on the branch and analysis performed:
-  Topic branches use preview analysis so "Diff" 
- Main branches "master, maint..." use standard analysis and then retrieve the issues from the api, so "Issues"

Hopefully I can make the aforementioned changes and PR when I have time, nice to know the release date :) keep up the good work!

Will there be any release of the old warnings plugin containing the last parsers?

**Comment by uhafner** [comment]
I added two issues, so we won't forget the open tasks:
- https://issues.jenkins-ci.org/browse/JENKINS-52462
- https://issues.jenkins-ci.org/browse/JENKINS-52463

**Comment by uhafner** [comment]
> In our use case we use each parser depending on the branch and analysis performed:
> Topic branches use preview analysis so "Diff"
> Main branches "master, maint..." use standard analysis and then retrieve the issues from the api, so "Issues"

I understand, but is it possible to detect which parser to use for which file? Then the user can just select "SonarQube". Otherwise the user needs to decide, which format to use...

**Comment by uhafner** [comment]
> Will there be any release of the old warnings plugin containing the last parsers?

I can make one if you can't wait for the new release...

**Comment by CarlesCapdevila** [comment]
>> Will there be any release of the old warnings plugin containing the last parsers?

> I can make one if you can't wait for the new release...

We only need the SQ parsers and we can build it locally for that, so I think there's no need to hurry for a new release. We'll survive ;)

**Pull request merged**
