### PR TITLE
WIP - Ansi Color handling

### PR DESCRIPTION
**Pull request by carpnick**
Opening a WIP to track.

### CODE REVIEW

**Comment by uhafner** [comment]
I can confirm that this is something general. If I enable global timestamps for pipelines then every job log cannot be parsed anymore because of the color codes:

```
[2019-03-09T19:12:04.459Z] [INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ analysis-model ---
  [2019-03-09T19:12:05.864Z] [INFO] Changes detected - recompiling the module!
  [2019-03-09T19:12:05.864Z] [INFO] Compiling 174 source files to /var/data/workspace/pipeline-analysis-model/target/classes
  [2019-03-09T19:12:23.994Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/NagFortranParser.java:[11,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.994Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/DrMemoryParser.java:[13,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/YuiCompressorParser.java:[10,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/DoxygenParser.java:[11,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/GnuFortranParser.java:[10,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/parser/GhsMultiParser.java:[11,30] edu.hm.hafner.analysis.RegexpDocumentParser in edu.hm.hafner.analysis has been deprecated
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/util/XmlElementUtil.java:[68,33] [MixedMutabilityReturnType] This method returns both mutable and immutable collections or maps from different paths. This may be confusing for users of the method.
  [2019-03-09T19:12:23.995Z]     (see https://errorprone.info/bugpattern/MixedMutabilityReturnType)
  [2019-03-09T19:12:23.995Z]   Did you mean 'public static ImmutableList<Element> nodeListToList(@Nullable final NodeList nodeList) {'?
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/FilteredLog.java:[112,107] [FormatStringAnnotation] Format strings must be compile time constants or parameters annotated @FormatString: s
  [2019-03-09T19:12:23.995Z]     (see https://errorprone.info/bugpattern/FormatStringAnnotation)
  [2019-03-09T19:12:23.995Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/Report.java:[82,44] [ConstructorLeaksThis] Constructors should not pass the 'this' reference out in method invocations, since the object may not be fully constructed.
  [2019-03-09T19:12:23.996Z]     (see https://errorprone.info/bugpattern/ConstructorLeaksThis)
  [2019-03-09T19:12:23.996Z] [WARNING] /var/data/workspace/pipeline-analysis-model/src/main/java/edu/hm/hafner/analysis/Report.java:[100,44] [ConstructorLeaksThis] Constructors should not pass the 'this' reference out in method invocations, since the object may not be fully constructed.
 
```

**Comment by uhafner** [comment]
Do you need some help with this PR?

**Comment by carpnick** [comment]
Just have not had time to work on it.  Will try to make some time in the coming week or 2

**Comment by carpnick** [comment]
After looking at your suggestions in a bit more detail....

- Color Codes - This is generic of the tool and has nothing to do with Jenkins, so it makes sense to include the filtering in this library instead of doing it in the warnings plugin (my opinon)
- For timestamps (generically removing those) - I think it would make more sense to remove those within your [ConsoleReaderFactory](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/src/main/java/io/jenkins/plugins/analysis/core/util/ConsoleLogReaderFactory.java#L29) due to it being very specific to Jenkins.

As far as the regex needed to filter our the color codes.  I looked online for awhile looking for filtering out color codes and anything prefixing it (thinking here is any formatting prefixing the log lines should be removed since color codes are always in front of line).  Using this [regex](https://www.regextester.com/?fam=108758) I was able to accomplish it.

Some helpful research:
- https://stackoverflow.com/a/14652763
- https://github.com/chalk/ansi-regex/blob/master/index.js#L3
- https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by uhafner** [comment]
I think this makes sense. Remove color codes here in this plugin. The timestamps are not so generic and need to be removed separately. 

What we should make more generally: remove the color codes somewhere on the line. E.g., a Maven report looks like:
```
[^[[1;34mINFO^[[m] Scanning for projects...
[^[[1;34mINFO^[[m]
[^[[1;34mINFO^[[m] ^[[1m--------------------< ^[[0;36medu.hm.hafner:analysis-model^[[0;1m >--------------------^[[m
[^[[1;34mINFO^[[m] ^[[1mBuilding Static Analysis Model and Parsers 4.1.0-SNAPSHOT^[[m
[^[[1;34mINFO^[[m] ^[[1m--------------------------------[ jar ]---------------------------------^[[m
[^[[1;34mINFO^[[m]
[^[[1;34mINFO^[[m] ^[[1m--- ^[[0;32mmaven-dependency-plugin:2.8:tree^[[m ^[[1m(default-cli)^[[m @ ^[[36manalysis-model^[[0;1m ---^[[m
[^[[1;34mINFO^[[m] edu.hm.hafner:analysis-model:jar:4.1.0-SNAPSHOT
[^[[1;34mINFO^[[m] +- com.github.spotbugs:spotbugs-annotations:jar:3.1.12:compile
[^[[1;34mINFO^[[m] |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[^[[1;34mINFO^[[m] +- com.google.errorprone:error_prone_annotations:jar:2.3.3:compile
[^[[1;34mINFO^[[m] +- org.apache.commons:commons-lang3:jar:3.8.1:compile
[^[[1;34mINFO^[[m] +- commons-io:commons-io:jar:2.6:compile
[^[[1;34mINFO^[[m] +- org.apache.commons:commons-digester3:jar:3.2:compile

```
So what should remain is the [INFO].

**Comment by uhafner** [comment]
A good place to do the filtering is in [ReaderFactory](https://github.com/jenkinsci/analysis-model/blob/master/src/main/java/edu/hm/hafner/analysis/ReaderFactory.java#L59):
```
this.lineMapper = lineMapper.compose(yourFunctionThatReplacesRegexpWithEmpty);
```

**Comment by uhafner** [comment]
Fixed with https://github.com/jenkinsci/analysis-model/commit/b801393cb30dda4ea49889e98595c4ada9df12b4.

Thank you for your work and investigations!

**Pull request closed without merging**
