### PR TITLE
add a line that should point to the position

### PR DESCRIPTION
**Pull request by ferkulat**
Some times there are several warnings in one code line.
If those warnings are of the same type, the webview of the code in question is not clear about the exact position.
In the following screenshot you see a warning that is created 3 times for the same line, but for different columns.
webview1

The easy fix is to construct a multi line message, with the first line containing a pointer on `column` of the warning.
the message could look like
webview
This has some issues as you might notice in the screen shot:
- the `^` should be right below `b` in the code line
- the icon offsets the start of the line
- the message font does not have fixed width

A possible solution could be:
- the warning text should use a fixed width font. Maybe even the same as it is used to display the code
- the icon could be displayed at the end of the warning

I made it work via trial and error in warnings-ng-plugin https://github.com/jenkinsci/warnings-ng-plugin/pull/1127 :
warnings-ng-proposal

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

<!--
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md 
You can override it by creating .github/pull_request_template.md  in your own repository 
--
>

### CODE REVIEW

**Comment by ferkulat** [comment]
@uhafner May I ask you what exactly triggers the creation of an incremental build?
Today for another pull request I was somehow able to make that work, but here it is missing.
in the following PR it worked and I don't know why:
https://github.com/jenkinsci/analysis-model/pull/714

Tried to add commits and push. Tried to force push a rebased branch. I have no clue. 

is the incremental build for `analysis-model` the only way to create `analysis-model-api-plugin`  with a modified `analysis-model`?

**Comment by uhafner** [comment]
The build is only published if your branch is up to date with master. You need to rebase or merge with master first.

**Comment by uhafner** [comment]
Wouldn't it make more sense to change the visualization in general? It would make sense to mark the column start and end in the source code with a CSS class and then highlight that part using CSS (squiggles or something like the [braces plugin](https://prismjs.com/plugins/match-braces/)).

**Comment by ferkulat** [comment]
@uhafner oh no I did not see your message, before creating a non draft PR.

You are right. It would be better to change visualization.
But at the moment the information about the column, seems to get lost on the way to the warnings-plugin.
Thats why I took the short cut to encode this in the message.

**Pull request closed without merging**
